export const ERROR_CODES = {
  NO_CALPINAGE_DATA: "NO_CALPINAGE_DATA",
  CALPINAGE_INCOMPLETE: "CALPINAGE_INCOMPLETE",
  SHADING_NOT_COMPUTED: "SHADING_NOT_COMPUTED",
  SNAPSHOT_TOO_RECENT: "SNAPSHOT_TOO_RECENT",
  CALPINAGE_INVALID_JSON: "CALPINAGE_INVALID_JSON",
};
