import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import express from 'express';import {PDFDocument} from 'pdf-lib';
import {geometryHash,hash,readTreeState,stateDirectory,automaticZeroAttestation} from '../services/shading/trees/crmState.js';import {createTreeShadingRouter} from '../services/shading/trees/crmRouter.js';import {appendTreeAnalysis} from '../services/shading/trees/pdfAppend.js';
const g={roofState:{map:{centerLatLng:{lat:49,lng:2}},scale:{metersPerPixel:.1},image:{width:100,height:100}},pans:[],frozenBlocks:[{panId:'r',panels:[{projection:{points:[{x:5,y:5}]}}]}]};
test('physical geometry invalidates; metadata does not; legacy results remain readable',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'phase3-trees-'));const dir=stateDirectory(root,'org','version');await fs.mkdir(dir);await fs.writeFile(path.join(dir,'crm-state.json'),JSON.stringify({geometryHash:hash(g),result:{status:'computed'}}));assert(await readTreeState(root,'org','version',g));assert.equal(geometryHash(g),geometryHash({...g,savedAt:'later',shading:{status:'pending'}}));const moved=structuredClone(g);moved.frozenBlocks[0].panels[0].projection.points[0].x++;assert.notEqual(geometryHash(g),geometryHash(moved));assert.equal(await readTreeState(root,'org','version',moved),null);});
test('complete empty IGN acquisition computes zero; incomplete empty acquisition fails closed',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'phase3-trees-'));let complete=true;
 const scene={status:'available',origin:{lat:49,lon:2,north:[0,1]},roofSurveyRequired:false,trees:[],panels:[{id:'P1',polygon:[[-.5,-.5,1],[.5,-.5,1],[.5,.5,1],[-.5,.5,1]]}],roofs:[{polygon:[[0,0,1]],plane:[0,0,1]}]};
 const hourly=Array.from({length:8760},(_,i)=>{const s=new Date(Date.UTC(2023,0,1,i)).toISOString();return {time:s.slice(0,10).replaceAll('-','')+':'+s.slice(11,16).replace(':',''),'Gb(i)':s.slice(11,13)==='12'?100:0,'Gd(i)':10,'Gr(i)':0};});
 const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={organizationId:'org'};next();});app.use('/s/:studyId/v/:versionId',createTreeShadingRouter({dataDir:root,loadStudy:async()=>({id:'version',geometry:g}),acquire:async(_,dir)=>{await fs.writeFile(path.join(dir,'irradiation.json'),JSON.stringify({inputs:{location:{latitude:49,longitude:2}},outputs:{hourly}}));return {...scene,acquisition:{complete}};}}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const post=p=>fetch(`http://127.0.0.1:${server.address().port}/s/study/v/1`+p,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
 try{assert.equal((await post('/acquire')).status,200);const r=await post('/calculate');assert.equal(r.status,200);const result=await r.json();assert.equal(result.status,'computed');assert.equal(result.lossPercent,0);assert.deepEqual([result.uncertainty.low,result.uncertainty.central,result.uncertainty.high],[0,0,0]);complete=false;await post('/acquire');assert.equal((await post('/calculate')).status,422);assert(!automaticZeroAttestation({...scene,status:'unavailable',acquisition:{complete:true}}));assert(!automaticZeroAttestation({...scene,roofSurveyRequired:true,acquisition:{complete:true}}));}finally{server.close();}
});
test('PDF omits absent/stale analysis, includes computed zero, rejects a changed result',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'phase3-trees-'));const doc=await PDFDocument.create();doc.addPage();const bytes=Buffer.from(await doc.save());let loads=0;const context={organizationId:'org',versionId:'version',loadGeometry:async()=>{loads++;return g;}},render=async()=>bytes;assert.deepEqual(await appendTreeAnalysis(bytes,context,{root,render}),bytes);assert.equal(loads,0);const dir=stateDirectory(root,'org','version');await fs.mkdir(dir);const state={geometryFingerprint:geometryHash(g),scene:{},revision:0,result:{status:'computed',lossPercent:0,hash:'valid'}},file=path.join(dir,'crm-state.json');await fs.writeFile(file,JSON.stringify(state));assert.equal((await PDFDocument.load(await appendTreeAnalysis(bytes,context,{root,render}))).getPageCount(),2);assert.deepEqual(await appendTreeAnalysis(bytes,{...context,loadGeometry:async()=>({...g,pans:[{id:'new'}]})},{root,render}),bytes);await assert.rejects(()=>appendTreeAnalysis(bytes,context,{root,render:async()=>{await fs.writeFile(file,JSON.stringify({...state,result:null}));return bytes;}}),/modifiée/);});
