import {test,mock} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {stateDirectory,geometryHash} from '../services/shading/trees/crmState.js';import {toStudyShading} from '../services/shading/trees/studyResult.js';
process.env.SHADING_ATTESTATION_SECRET='fictional-local-quote-test-only-000000000';process.env.SHADING_ATTESTATION_KEY_ID='local-tests';const root=await fs.mkdtemp(path.join(os.tmpdir(),'unified-quote-'));process.env.TREE_SHADING_DATA_DIR=root;
const geometry={panels:{count:10},pans:[]};const dir=stateDirectory(root,'org','version');await fs.mkdir(dir);
mock.module('../config/db.js',{namedExports:{pool:{query:async(sql)=>{assert.match(sql.trim(),/^SELECT/);if(sql.includes('FROM study_versions'))return {rows:[{id:'version',study_id:'study'}]};if(sql.includes('FROM calpinage_data'))return {rows:[{total_panels:10,total_power_kwc:5,total_loss_pct:7,geometry_json:geometry}]};if(sql.includes('FROM studies'))return {rows:[{id:'study'}]};return {rows:[]};}}}});
const {getQuotePrep}=await import('../services/quotePrep/quotePrep.service.js');
const params={organizationId:'org',versionId:'version',studyId:'study'};
function result(loss){const r={scope:'combined-shading-v1',status:'computed',hash:'global-'+loss,lossPercent:loss,components:{trees:{lossPercent:loss},obstacles:{lossPercent:0},horizon:{lossPercent:0}},panels:[],months:Array.from({length:12},(_,i)=>({month:i+1,baseline:100,lossPercent:loss,horizonLost:0,nearLost:loss}))};r.shading=toStudyShading(r);return r;}
test('real quote-prep reads the same saved global result, never the legacy snapshot loss',async()=>{for(const loss of [32.98731210186241,0]){await fs.writeFile(path.join(dir,'crm-state.json'),JSON.stringify({pipelineVersion:'unified-v1',geometryFingerprint:geometryHash(geometry),result:result(loss)}));const q=(await getQuotePrep(params)).technical_snapshot_summary;assert.equal(q.shading_pct,loss);assert.equal(q.total_loss_pct,loss);assert.equal(q.shading_result_hash,'global-'+loss);}});
test('real quote-prep clears obsolete losses after skip or geometry changes',async()=>{for(const excluded of [true,false]){await fs.writeFile(path.join(dir,'crm-state.json'),JSON.stringify({pipelineVersion:'unified-v1',geometryFingerprint:excluded?geometryHash(geometry):'old',result:excluded?null:result(32.99),excluded}));const q=(await getQuotePrep(params)).technical_snapshot_summary;assert.equal(q.shading_pct,null);assert.equal(q.total_loss_pct,null);assert.equal(q.shading_result_hash,null);}});
