/**
 * Codes diagnostics officiels — validation géométrique / topologique Maison 3D.
 * Stables pour QA, viewer, exports (ne pas renommer sans migration).
 */

export type CanonicalHouse3DValidationCode =
  // Bâtiment
  | "BUILDING_FOOTPRINT_INVALID"
  | "BUILDING_SHELL_MISSING"
  | "BUILDING_SHELL_OPEN"
  | "BUILDING_WALL_DEGENERATE"
  | "BUILDING_WALL_ZERO_LENGTH"
  | "BUILDING_HEIGHT_INCONSISTENT"
  | "BUILDING_NORMAL_INVERTED"
  | "BUILDING_SHELL_DIAGNOSTIC_FAILED"
  // Topologie toit
  | "ROOF_PATCH_DEGENERATE"
  | "ROOF_TOPOLOGY_INVALID"
  | "ROOF_TOPOLOGY_AMBIGUOUS"
  | "ROOF_EDGE_FLOATING"
  | "ROOF_SHARED_EDGE_INCONSISTENT"
  | "ROOF_PATCH_BOUNDARY_OPEN"
  // Plans toit
  | "ROOF_PLANE_MISSING"
  | "ROOF_PLANE_QUASI_VERTICAL_UNSUPPORTED"
  | "ROOF_PLANE_RESIDUAL_TOO_HIGH"
  | "ROOF_PLANE_UNDERCONSTRAINED"
  | "ROOF_PLANE_CONFLICTING"
  | "ROOF_PLANE_FALLBACK_USED"
  | "ROOF_PLANE_SOLUTION_SET_INVALID"
  // Intersections
  | "ROOF_INTERSECTION_GAP_TOO_HIGH"
  | "ROOF_INTERSECTION_STEP_TOO_HIGH"
  | "ROOF_INTERSECTION_MISSING"
  | "ROOF_INTERSECTION_INCONSISTENT"
  | "ROOF_INTERSECTION_SET_INVALID"
  | "ROOF_INTERSECTION_SEWING_PARTIAL"
  | "ROOF_INTERSECTION_SEWING_AMBIGUOUS"
  // Binding toit ↔ bâtiment
  | "ROOF_BINDING_INVALID"
  | "ROOF_EAVE_UNSUPPORTED"
  | "ROOF_EAVE_FLOATING"
  | "ROOF_EAVE_MISALIGNED"
  | "ROOF_GABLE_INCONSISTENT"
  | "ROOF_RIDGE_FREE_UNSUPPORTED"
  | "ROOF_OVERHANG_AMBIGUOUS"
  | "ROOF_NOT_ATTACHED_TO_BUILDING"
  // Annexes
  | "ANNEX_LAYER_MISSING_OPTIONAL"
  | "ANNEX_NO_HOST_PATCH"
  | "ANNEX_BINDING_AMBIGUOUS"
  | "ANNEX_VOLUME_INVALID"
  | "ANNEX_HEIGHT_MISSING"
  | "ANNEX_NEEDS_TOPOLOGY_SPLIT"
  | "ANNEX_EDGE_UPLIFT_DEFERRED"
  // Global
  | "HOUSE_GEOMETRY_INCOMPLETE"
  | "HOUSE_GEOMETRY_AMBIGUOUS"
  | "HOUSE_GEOMETRY_PARTIAL"
  | "HOUSE_GEOMETRY_INVALID"
  | "HOUSE_NORMALS_GLOBAL_WARNING";

export const CANONICAL_HOUSE_3D_VALIDATION_REPORT_SCHEMA_ID = "canonical-house-3d-validation-report-v1" as const;
