/**
 * Fallbacks tarifaires batterie virtuelle (hors grille org exploitable).
 * Valeurs centralisées dans services/core/engineConstants.js — tout changement doit être reflété dans
 * frontend/src/constants/virtualBatteryLegacyDefaults.ts
 */

import {
  VB_LEGACY_MYSMART_CONTRIBUTION_FIXED_EUR_PER_YEAR_HT,
  VB_LEGACY_MYSMART_CONTRIBUTION_PER_KVA_EUR_PER_YEAR_HT,
  VB_LEGACY_DEFAULT_AUTOPROD_CONTRIBUTION_EUR_PER_YEAR_HT,
  VB_LEGACY_MYBATTERY_ACTIVATION_FEE_HT,
  VB_LEGACY_MYBATTERY_BASE_DISCHARGE_EUR_PER_KWH_HT,
  VB_LEGACY_MYBATTERY_HPHC_HP_DISCHARGE_EUR_PER_KWH_HT,
  VB_LEGACY_MYBATTERY_HPHC_HC_DISCHARGE_EUR_PER_KWH_HT,
  VB_LEGACY_URBAN_BASE_GRID_FEE_EUR_PER_KWH_HT,
  VB_LEGACY_URBAN_HPHC_HP_DISCHARGE_SUM_HT,
  VB_LEGACY_URBAN_HPHC_HC_DISCHARGE_SUM_HT,
} from "../core/engineConstants.js";

export {
  VB_LEGACY_MYSMART_CONTRIBUTION_FIXED_EUR_PER_YEAR_HT,
  VB_LEGACY_MYSMART_CONTRIBUTION_PER_KVA_EUR_PER_YEAR_HT,
  VB_LEGACY_DEFAULT_AUTOPROD_CONTRIBUTION_EUR_PER_YEAR_HT,
  VB_LEGACY_MYBATTERY_ACTIVATION_FEE_HT,
  VB_LEGACY_MYBATTERY_BASE_DISCHARGE_EUR_PER_KWH_HT,
  VB_LEGACY_MYBATTERY_HPHC_HP_DISCHARGE_EUR_PER_KWH_HT,
  VB_LEGACY_MYBATTERY_HPHC_HC_DISCHARGE_EUR_PER_KWH_HT,
  VB_LEGACY_URBAN_BASE_GRID_FEE_EUR_PER_KWH_HT,
  VB_LEGACY_URBAN_HPHC_HP_DISCHARGE_SUM_HT,
  VB_LEGACY_URBAN_HPHC_HC_DISCHARGE_SUM_HT,
} from "../core/engineConstants.js";

/** Contribution autoproducteur MySmart historique (€/an HT) si pas de contributionRule admin. */
export function vbLegacyMySmartAnnualContributionHt(meterKva) {
  const kv = Number(meterKva);
  const k = Number.isFinite(kv) ? kv : 0;
  return (
    VB_LEGACY_MYSMART_CONTRIBUTION_FIXED_EUR_PER_YEAR_HT +
    VB_LEGACY_MYSMART_CONTRIBUTION_PER_KVA_EUR_PER_YEAR_HT * k
  );
}
